name: app
type: 'php:8.4'

web:
  locations:
    '/':
      root: 'web'
      index: index.php
      allow: true
      passthru: '/index.php'

mounts:
  'web/uploads':
    source: local
    source_path: uploads

disk: 256

relationships:
  mariadb: 'mariadb:mysql'
